# SVM - Support Vector Machine 

**It is a machine learning algorithm that is used for classification and Regression Problem.**

# Goal of the SVM 

**Goal is to find a line or decision boundry to seprate two or more classes.**

# how is it work 

**It draw a line or boundry to seprate two classes.**

**It choeses a line that is as far as two nearst data points of each group.These nearst two data points are called support vector.**

# Hyper Plane 

**The decision boundry that seprate classes**

# Margin 

**The distance between the hperplane and two nearst data points from each class. SVM tries to maximise the margin to make the sepration robust**

# Real life example is 

**to detech email is spam or not**

# Advantages 

**Works well with the dataset with larget number of features**

**Robust for overfitting- for the senarios where number of samples is less than the number of features**

**Works well with clear marging**

# Disadvantages 

**Computional Complexity- Training can be slow for large dataset**

**Chossing the right kernal- to chose right kernal and heyperparameter is experimental**


# Key Takeaways:

**Logistic Regression:** Best for binary classification and scenarios requiring interpretability.

**Decision Tree:** Good for non-linear problems, but needs pruning to avoid overfitting.

**Random Forest:** Balances bias and variance effectively and works well for large datasets.

**SVM:** Ideal for high-dimensional, small datasets but computationally intensive.

**Naive Bayes:** Excellent for text-based tasks with categorical data.

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
!pip install gdown

Collecting gdown
  Downloading gdown-6.1.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/lib/python3.13/site-packages (from gdown) (4.12.3)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.13/site-packages (from gdown) (3.17.0)
Requirement already satisfied: requests[socks] in /opt/anaconda3/lib/python3.13/site-packages (from gdown) (2.33.1)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4->gdown) (2.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests[socks]->gdown) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests[socks]->gdown) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/lib/python3.13/site-packages (from requests[socks]->gdown) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/anaconda3/lib/python3.13/site-packages (from requests[socks]->gdown) (2025.6.15)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /opt/anaconda3/lib/python3.13/site-packages (from requests[socks]->gdown) (1.7.1)
Downloading gdown-6.1.0-py3-none-any.whl (19 kB)
Installing collected packages: gdown
Successfully installed gdown-6.1.0

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [7]:
import gdown
url = 'https://drive.google.com/file/d/1TPIbsCdJrCcs5JUQn3wPpOPmfmybUCbS/view?usp=sharing'
gdown.download(url, "downloaded_file")

Downloading...
From: https://drive.google.com/uc?id=1TPIbsCdJrCcs5JUQn3wPpOPmfmybUCbS
To: /Users/anuragpanchal/Documents/MachineLearning/SVM/downloaded_file
100%|██████████| 6.03k/6.03k [00:00<00:00, 182kB/s]

'downloaded_file'

In [8]:
df = pd.read_csv('/Users/anuragpanchal/Documents/MachineLearning/SVM/downloaded_file')

In [9]:
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [11]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [15]:
df['Drug'].nunique()

5

In [16]:
df['Drug'].value_counts()

Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [19]:
from sklearn.preprocessing import LabelEncoder
for i in df.columns:
    le = LabelEncoder()
    df[i]= le.fit_transform(df[i])

In [20]:
df

     Age  Sex  BP  Cholesterol  Na_to_K  Drug
0      8    0   0            0      167     0
1     30    1   1            0       89     3
2     30    1   1            0       43     3
3     12    0   2            0       10     4
4     44    0   1            0      133     0
..   ...  ...  ..          ...      ...   ...
195   39    0   1            0       69     3
196    1    1   1            0       75     3
197   35    1   2            0       36     4
198    8    1   2            1      102     4
199   24    0   1            1       66     4

[200 rows x 6 columns]

In [22]:
x = df.drop(columns='Drug')
y= df['Drug']

In [23]:
x

     Age  Sex  BP  Cholesterol  Na_to_K
0      8    0   0            0      167
1     30    1   1            0       89
2     30    1   1            0       43
3     12    0   2            0       10
4     44    0   1            0      133
..   ...  ...  ..          ...      ...
195   39    0   1            0       69
196    1    1   1            0       75
197   35    1   2            0       36
198    8    1   2            1      102
199   24    0   1            1       66

[200 rows x 5 columns]

In [24]:
y

0      0
1      3
2      3
3      4
4      0
      ..
195    3
196    3
197    4
198    4
199    4
Name: Drug, Length: 200, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.20,random_state=0)

In [ ]:
 # By default kernel (RBF) function
from sklearn.svm import SVC
model1 =SVC()
model1.fit(x_train,y_train)
y_pred = model1.predict(x_test)
from sklearn.metrics import *
accuracy_score(y_test,y_pred)*100

82.5

In [36]:
# Linear Kernel Function
model1 =SVC(kernel='linear')
model1.fit(x_train,y_train)
y_pred = model1.predict(x_test)
from sklearn.metrics import *
accuracy_score(y_test,y_pred)*100

97.5

In [37]:
# RBF Kernel Function
model1 =SVC(kernel='rbf')
model1.fit(x_train,y_train)
y_pred = model1.predict(x_test)
from sklearn.metrics import *
accuracy_score(y_test,y_pred)*100

82.5

In [38]:
# POLYNOMIAL Kernel Function
model1 =SVC(kernel='poly')
model1.fit(x_train,y_train)
y_pred = model1.predict(x_test)
from sklearn.metrics import *
accuracy_score(y_test,y_pred)*100

82.5

# Kernal Function - 
**It is used to transform the  input data into higher dimensional space .This enables svm to find linear boundry in the higher dimensional space even the data is non linearly seprable in it orginal dimension.**

# 1)Linear Kernel:

A simple kernel that works by drawing a straight line or hyperplane to separate the data into classes.

Used when the data is linearly separable.

# 2)Polynomial Kernel:

A kernel that considers the similarity of points based on polynomial relationships.

Effective for data where relationships between features are more complex but still follow a specific pattern.

# )Radial Basis Function (RBF) Kernel:

A popular kernel that measures the similarity between points based on their distance.

It is widely used for non-linear data and can handle complex patterns.

# 4)Sigmoid Kernel:

A kernel similar to the activation function used in neural networks.

It can model non-linear relationships but is less commonly used compared to other kernels.